### PR TITLE
Start a Guide to Leeds

### PR DESCRIPTION
**Pull request by mikaelacaron**
* Add a `.editorconfig` to help everyone with formatting
* Add `HomeView` and `SettingsView` into a `TabView`
* Add a list as a guide to places around Leeds to go to after the conference

### CODE REVIEW

**Comment by mikaelacaron** [comment]
@adamrushy

**Review by roddymunro — APPROVED** [review]

**Comment by roddymunro** [comment]
:shipit:

**Comment by mikaelacaron** [comment]
@roddymunro @Oliver-Binns if you guys are cool with it, we can add a `CODEOWNERS` file too, that makes it so you both get automatically assigned PRs when they're created

**Review by NickAtGit — APPROVED** [review]
LGTM!

**Pull request merged**
